name: Deploy Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: amazon-linux-2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Ansible playbook
        uses: ansible/ansible-playbook-action@v2.1.0
        with:
          path: /home/ec2-user/webservers.yaml

